<template>
  <main class="mx-auto max-w-5xl space-y-6 p-6 lg:p-8">
    <UButton
      to="/proposals"
      icon="i-lucide-arrow-left"
      color="neutral"
      variant="link"
      class="-ml-2"
    >
      Back to proposals
    </UButton>

    <!-- Loading skeleton -->
    <div v-if="pending" class="space-y-6">
      <USkeleton class="h-32 w-full rounded-2xl bg-neutral-200" />
      <div class="grid gap-6 lg:grid-cols-5">
        <div class="space-y-4 lg:col-span-3">
          <USkeleton class="h-40 w-full rounded-2xl bg-neutral-200" />
          <USkeleton class="h-52 w-full rounded-2xl bg-neutral-200" />
        </div>
        <USkeleton class="h-64 w-full rounded-2xl bg-neutral-200 lg:col-span-2" />
      </div>
    </div>

    <p v-else-if="error" class="text-sm text-red-600">
      Couldn't load this proposal. Please try again.
    </p>

    <template v-else-if="proposal">
      <section
        class="flex flex-col justify-between gap-4 rounded-2xl bg-black p-6 text-white md:flex-row md:items-start"
      >
        <div>
          <p class="text-sm text-[#e0b818]">Proposal #{{ proposal.proposal_id }}</p>
          <h1 class="mt-1 text-2xl font-semibold">
            {{ proposal.client?.company || "Untitled client" }}
          </h1>
          <p class="mt-3 text-sm text-neutral-300">
            {{ proposal.client?.name || "—" }} · Version {{ proposal.version }} ·
            Generated by {{ proposal.generated_by || "Kora AI" }}
          </p>
        </div>
        <div class="flex items-center gap-3">
          <UBadge :color="statusColor(proposal.status)" variant="subtle">
            {{ proposal.status }}
          </UBadge>
          <UButton icon="i-lucide-pencil" class="text-white" @click="editOpen = true">
            Edit draft
          </UButton>
        </div>
      </section>

      <section class="grid gap-6 lg:grid-cols-5">
        <div class="space-y-6 lg:col-span-3">
          <UCard :ui="{ root: 'ring-0 border border-neutral-200 !bg-white shadow-sm' }">
            <template #header>
              <h2 class="font-semibold text-neutral-950">Scope of work</h2>
            </template>
            <p class="whitespace-pre-line text-sm leading-7 text-neutral-600">
              {{ proposal.scope_of_work || "Not yet established." }}
            </p>
          </UCard>

          <UCard :ui="{ root: 'ring-0 border border-neutral-200 !bg-white shadow-sm' }">
            <template #header>
              <h2 class="font-semibold text-neutral-950">Deliverables</h2>
            </template>
            <ul v-if="proposal.deliverables?.length" class="space-y-2">
              <li
                v-for="(item, i) in proposal.deliverables"
                :key="i"
                class="flex gap-2 text-sm text-neutral-700"
              >
                <span class="text-[#c59d00]">•</span>{{ item }}
              </li>
            </ul>
            <p v-else class="text-sm text-neutral-500">Not yet established.</p>
          </UCard>
        </div>

        <aside class="space-y-5 lg:col-span-2">
          <UCard :ui="{ root: 'ring-0 border border-neutral-200 !bg-white shadow-sm' }">
            <template #header>
              <h2 class="font-semibold text-neutral-950">Timeline</h2>
            </template>
            <p class="text-sm leading-6 text-neutral-700">
              {{ proposal.timeline || "Not yet established." }}
            </p>
          </UCard>

          <UCard :ui="{ root: 'ring-0 border border-neutral-200 !bg-white shadow-sm' }">
            <template #header>
              <h2 class="font-semibold text-neutral-950">Linked quotations</h2>
            </template>
            <div v-if="quotesPending" class="space-y-2">
              <USkeleton class="h-10 w-full bg-neutral-200" />
            </div>
            <ul v-else-if="quotes.length" class="space-y-3">
              <li
                v-for="quote in quotes"
                :key="quote.quote_id"
                class="flex items-center justify-between gap-3"
              >
                <div>
                  <p class="text-sm font-medium text-neutral-900">
                    Quote #{{ quote.quote_id }}
                  </p>
                  <p class="text-xs text-neutral-500">
                    {{ quote.currency }} {{ formatNumber(quote.total ?? quote.total_amount) }}
                  </p>
                </div>
                <UButton
                  :to="`/quotations/${quote.quote_id}`"
                  size="xs"
                  color="neutral"
                  variant="outline"
                >
                  View
                </UButton>
              </li>
            </ul>
            <p v-else class="text-sm text-neutral-500">No quotations yet.</p>
          </UCard>
        </aside>
      </section>
    </template>

    <EditProposalModal
      v-model="editOpen"
      :proposal="proposal"
      @saved="onSaved"
    />
  </main>
</template>

<script setup lang="ts">
const route = useRoute();
const proposalId = route.params.id as string;

const editOpen = ref(false);

const {
  data: proposal,
  pending,
  error,
  refresh,
} = await useLazyFetch<any>(`/api/proposals/${proposalId}`);

const { data: quotesData, pending: quotesPending } = await useLazyFetch<{
  data: any[];
}>("/api/quotes", { query: { proposal_id: proposalId } });

const quotes = computed(() => quotesData.value?.data ?? []);

function statusColor(status: string) {
  if (status === "accepted") return "success";
  if (status === "sent" || status === "revised") return "warning";
  if (status === "rejected") return "error";
  return "neutral";
}

function formatNumber(n: number) {
  return Number(n ?? 0).toLocaleString();
}

async function onSaved(updated: any) {
  proposal.value = updated;
  await refresh();
}
</script>
