import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import html2pdf from "html2pdf.js";

const A4_WIDTH_PX = 794;
const A4_HEIGHT_PX = 1123;

async function downloadRenderedProposalTemplate(proposal: any) {
  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.left = "-10000px";
  iframe.style.top = "0";
  iframe.style.width = `${A4_WIDTH_PX}px`;
  iframe.style.height = `${A4_HEIGHT_PX}px`;
  iframe.style.border = "none";
  document.body.appendChild(iframe);

  try {
    await new Promise<void>((resolve) => {
      iframe.onload = () => resolve();
      iframe.srcdoc = proposal.proposal_html;
    });

    // `onload` only guarantees the iframe's DOM has parsed, not that layout/paint
    // has settled — give the browser two frames before handing it to html2canvas,
    // otherwise the capture can come back blank.
    await new Promise<void>((resolve) => {
      requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
    });

    const target = iframe.contentDocument?.body;
    if (!target) return false;

    await html2pdf()
      .set({
        margin: 0,
        filename: `proposal_${proposal.proposal_id}.pdf`,
        html2canvas: { scale: 2, useCORS: true, windowWidth: A4_WIDTH_PX },
        jsPDF: { unit: "pt", format: "a4", orientation: "portrait" },
      })
      .from(target)
      .save();

    return true;
  } finally {
    document.body.removeChild(iframe);
  }
}

export async function downloadProposalPdf(proposal: any) {
  if (proposal?.proposal_html) {
    const rendered = await downloadRenderedProposalTemplate(proposal);
    if (rendered) return;
  }

  const pdf = await PDFDocument.create();

  let page = pdf.addPage([595.28, 841.89]); // A4

  const { width, height } = page.getSize();

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const margin = 50;
  const lineHeight = 18;

  let y = height - margin;

  const ensureSpace = (required = 40) => {
    if (y < required) {
      page = pdf.addPage([595.28, 841.89]);
      y = height - margin;
    }
  };

  const title = (text: string) => {
    ensureSpace(60);
    page.drawText(text, { x: margin, y, size: 18, font: bold, color: rgb(0.18, 0.18, 0.18) });
    y -= 28;
  };

  const heading = (text: string) => {
    ensureSpace(40);
    page.drawText(text, { x: margin, y, size: 13, font: bold, color: rgb(0.72, 0.55, 0.05) });
    y -= 20;
  };

  const wrap = (text: string, maxChars = 90): string[] => {
    const words = text.split(/\s+/);
    const lines: string[] = [];
    let line = "";
    for (const word of words) {
      if ((line + " " + word).trim().length > maxChars) {
        if (line) lines.push(line);
        line = word;
      } else {
        line = (line + " " + word).trim();
      }
    }
    if (line) lines.push(line);
    return lines;
  };

  const body = (text: string) => {
    for (const line of wrap(text)) {
      ensureSpace();
      page.drawText(line, { x: margin, y, size: 11, font });
      y -= lineHeight;
    }
  };

  const bullet = (text: string) => body(`• ${text}`);

  title("KORA AI");
  body("Proposal");
  body(new Date(proposal.created_at).toLocaleString());

  y -= 12;

  heading("Client");
  body(`Company: ${proposal.client?.company ?? "—"}`);
  body(`Contact: ${proposal.client?.name ?? "—"}`);

  y -= 8;

  heading("Scope of work");
  body(proposal.scope_of_work || "Not yet established.");

  y -= 8;

  heading("Deliverables");
  (proposal.deliverables ?? []).forEach((item: string) => bullet(item));

  y -= 8;

  heading("Timeline");
  body(proposal.timeline || "Not yet established.");

  y -= 8;

  heading("Status");
  body(`${proposal.status} · v${proposal.version}`);

  page.drawLine({
    start: { x: margin, y: 40 },
    end: { x: width - margin, y: 40 },
    thickness: 1,
  });

  page.drawText("Generated by Kora AI", {
    x: margin,
    y: 22,
    size: 10,
    font,
    color: rgb(0.45, 0.45, 0.45),
  });

  const bytes = await pdf.save();
  const blob = new Blob([bytes as BlobPart], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = `proposal_${proposal.proposal_id}.pdf`;
  link.click();

  URL.revokeObjectURL(url);
}
