import {
  PDFDocument,
  StandardFonts,
  rgb,
} from "pdf-lib";

export async function downloadSummaryPdf(summary: any) {
  const meeting = summary.first_meeting_deliverables;

  const pdf = await PDFDocument.create();

  let page = pdf.addPage([595.28, 841.89]); // A4

  const { width, height } = page.getSize();

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const margin = 50;
  const lineHeight = 18;

  let y = height - margin;

  const ensureSpace = (required = 40) => {
    if (y < required) {
      page = pdf.addPage([595.28, 841.89]);
      y = height - margin;
    }
  };

  const title = (text: string) => {
    ensureSpace(60);

    page.drawText(text, {
      x: margin,
      y,
      size: 18,
      font: bold,
      color: rgb(0.18, 0.18, 0.18),
    });

    y -= 28;
  };

  const heading = (text: string) => {
    ensureSpace(40);

    page.drawText(text, {
      x: margin,
      y,
      size: 13,
      font: bold,
      color: rgb(0.72, 0.55, 0.05),
    });

    y -= 20;
  };

  const body = (text: string) => {
    ensureSpace();

    page.drawText(text, {
      x: margin,
      y,
      size: 11,
      font,
    });

    y -= lineHeight;
  };

  const bullet = (text: string) => {
    body(`• ${text}`);
  };

  // ------------------------------------
  // Header
  // ------------------------------------

  title("KORA AI");
  body("Meeting Summary");
  body(new Date(summary.created_at).toLocaleString());

  y -= 12;

  // ------------------------------------
  // Meeting
  // ------------------------------------

  heading("Meeting");

  body(`Title: ${meeting.title}`);
  body(`Type: ${meeting.meeting_type}`);

  y -= 8;

  // ------------------------------------
  // Client
  // ------------------------------------

  heading("Client");

  body(
    `Company: ${meeting.key_points.client.company}`,
  );

  body(
    `Contact: ${meeting.key_points.client.primary_contact}`,
  );

  y -= 8;

  // ------------------------------------
  // Project
  // ------------------------------------

  heading("Project");

  body(
    `Name: ${meeting.key_points.project.name}`,
  );

  body(
    `Type: ${meeting.key_points.project.type}`,
  );

  body(
    `Objective: ${meeting.key_points.project.objective}`,
  );

  y -= 8;

  // ------------------------------------
  // Deliverables
  // ------------------------------------

  heading("Deliverables");

  meeting.key_points.deliverables.forEach((item: any) => {
    bullet(
      `${item.name}${
        item.duration ? ` (${item.duration})` : ""
      }`,
    );
  });

  y -= 8;

  // ------------------------------------
  // Timeline
  // ------------------------------------

  heading("Timeline");

  body(
    `Hackathon Ends: ${meeting.key_points.timeline.hackathon_end}`,
  );

  body(
    `Summary Video: ${meeting.key_points.timeline.summary_video_genesis_quote}`,
  );

  body(
    `Social Clips: ${meeting.key_points.timeline.social_clips_genesis_quote}`,
  );

  y -= 8;

  // ------------------------------------
  // Creative Direction
  // ------------------------------------

  heading("Creative Direction");

  body(
    meeting.key_points.creative_direction.description,
  );

  meeting.key_points.creative_direction.messaging_themes.forEach(
    (theme: string) => bullet(theme),
  );

  y -= 8;

  // ------------------------------------
  // Next Steps
  // ------------------------------------

  heading("Genesis Next Steps");

  meeting.key_points.next_steps.genesis.forEach(
    (step: string) => bullet(step),
  );

  y -= 8;

  heading("Client Next Steps");

  meeting.key_points.next_steps.client.forEach(
    (step: string) => bullet(step),
  );

  y -= 12;

  heading("Budget");

  body(meeting.key_points.budget.status);

  y -= 8;

  heading("Competition");

  body(
    `Other Agencies: ${meeting.key_points.competition.other_agencies}`,
  );

  body(
    `Selection: ${meeting.key_points.competition.selection_method}`,
  );

  // ------------------------------------
  // Footer
  // ------------------------------------

  page.drawLine({
    start: { x: margin, y: 40 },
    end: { x: width - margin, y: 40 },
    thickness: 1,
  });

  page.drawText("Generated by Kora AI", {
    x: margin,
    y: 22,
    size: 10,
    font,
    color: rgb(0.45, 0.45, 0.45),
  });

  const bytes = await pdf.save();

  const blob = new Blob([bytes], {
    type: "application/pdf",
  });

  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");

  link.href = url;

  link.download = `${meeting.title.replace(/\s+/g, "_")}_summary.pdf`;

  link.click();

  URL.revokeObjectURL(url);
}