import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function downloadQuotationPdf(quotation: any) {
  const pdf = await PDFDocument.create();

  let page = pdf.addPage([595.28, 841.89]); // A4

  const { width, height } = page.getSize();

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const margin = 50;
  const lineHeight = 18;

  let y = height - margin;

  const ensureSpace = (required = 40) => {
    if (y < required) {
      page = pdf.addPage([595.28, 841.89]);
      y = height - margin;
    }
  };

  const title = (text: string) => {
    ensureSpace(60);
    page.drawText(text, { x: margin, y, size: 18, font: bold, color: rgb(0.18, 0.18, 0.18) });
    y -= 28;
  };

  const heading = (text: string) => {
    ensureSpace(40);
    page.drawText(text, { x: margin, y, size: 13, font: bold, color: rgb(0.72, 0.55, 0.05) });
    y -= 20;
  };

  const body = (text: string) => {
    ensureSpace();
    page.drawText(text, { x: margin, y, size: 11, font });
    y -= lineHeight;
  };

  const currency = quotation.currency || "KES";
  const fmt = (n: number) => `${currency} ${Number(n ?? 0).toLocaleString()}`;

  title("KORA AI");
  body("Quotation");
  body(new Date(quotation.created_at).toLocaleString());

  y -= 12;

  heading("Line items");
  ensureSpace(40);
  page.drawText("Item", { x: margin, y, size: 10, font: bold });
  page.drawText("Qty", { x: 340, y, size: 10, font: bold });
  page.drawText("Unit price", { x: 400, y, size: 10, font: bold });
  page.drawText("Amount", { x: 490, y, size: 10, font: bold });
  y -= lineHeight;

  (quotation.line_items ?? []).forEach((item: any) => {
    ensureSpace();
    page.drawText(String(item.item ?? ""), { x: margin, y, size: 10, font });
    page.drawText(String(item.qty ?? 0), { x: 340, y, size: 10, font });
    page.drawText(fmt(item.unit_price), { x: 400, y, size: 10, font });
    page.drawText(fmt(item.amount), { x: 490, y, size: 10, font });
    y -= lineHeight;
  });

  y -= 12;

  heading("Totals");
  body(`Subtotal: ${fmt(quotation.subtotal)}`);
  body(`Tax rate: ${quotation.tax_rate ?? 0}%`);
  body(`Discount: ${fmt(quotation.discount_amount)}`);
  body(`Total: ${fmt(quotation.total ?? quotation.total_amount)}`);

  y -= 8;

  heading("Validity");
  body(`Valid for ${quotation.validity_days ?? 30} days · ${quotation.status}`);

  page.drawLine({
    start: { x: margin, y: 40 },
    end: { x: width - margin, y: 40 },
    thickness: 1,
  });

  page.drawText("Generated by Kora AI", {
    x: margin,
    y: 22,
    size: 10,
    font,
    color: rgb(0.45, 0.45, 0.45),
  });

  const bytes = await pdf.save();
  const blob = new Blob([bytes as BlobPart], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = `quotation_${quotation.quote_id}.pdf`;
  link.click();

  URL.revokeObjectURL(url);
}
